# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a457691c6f09e3710590ee2ef302054623fbc71a8020d3712eceb57a90063cf4e76f773dff05e20e4f64ebdb72bbe0dce7821f7a2302dd97881bbd1871b149

test:
  secret_key_base: 94eb9c94b4c946803511787dd44d0937fa0e61c0720fb56850d32f64b7e2dbe25f1481256f1c8d17aef91e6b04d8ff2de959632464572805e65a305da18fbc62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
